### ISSUE TITLE
Persistence Variable in upcoming cells

### ISSUE THREAD

**Issue by dilshaat** [vors/jupyter-powershell#19]
It seems that the Variable created in one cell does not persist in next cells. For example:

```ipython
$date = Get-Date
```
```ipython
$date   \# returns nothing
````
Is this feature possible to add?

**Comment by theaquamarine** [comment]
The issue is https://github.com/vors/jupyter-powershell/blob/9417d40b9541d4e0c690f936f62bd7f3a117f721/powershell_kernel/kernel.py#L58 using the call operator, which runs in a child scope. Switching to the dot source operator fixes this, though might cause other issues, depending what else shares that scope.
```python
self.proxy.send_input('. { ' + code + ' }')
```

**Comment by ambrose-leung** [comment]
Can whoever has permissions push the latest code so that it works with `pip install powershell_kernel`?

I had to do this manually.  i.e. replace the files in Anaconda3\Lib\site-packages\powershell_kernel and then run `python -m powershell_kernel.install`

**Comment by vors** [comment]
@chlafreniere can you make a 0.1.1 release with this fix?

**Comment by chlafreniere** [comment]
Of course. Let me get started on it 😄
